<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'rapture\\validator\\between' => '/../src/Between.php',
                'rapture\\validator\\cnp' => '/../src/Cnp.php',
                'rapture\\validator\\collection' => '/../src/Collection.php',
                'rapture\\validator\\country' => '/../src/Country.php',
                'rapture\\validator\\currency' => '/../src/Currency.php',
                'rapture\\validator\\definition\\validatorabstract' => '/../src/Definition/ValidatorAbstract.php',
                'rapture\\validator\\email' => '/../src/Email.php',
                'rapture\\validator\\emaildomain' => '/../src/EmailDomain.php',
                'rapture\\validator\\equalto' => '/../src/EqualTo.php',
                'rapture\\validator\\filesize' => '/../src/FileSize.php',
                'rapture\\validator\\filetype' => '/../src/FileType.php',
                'rapture\\validator\\greaterthan' => '/../src/GreaterThan.php',
                'rapture\\validator\\greaterthanorequalto' => '/../src/GreaterThanOrEqualTo.php',
                'rapture\\validator\\group' => '/../src/Group.php',
                'rapture\\validator\\identicalto' => '/../src/IdenticalTo.php',
                'rapture\\validator\\in' => '/../src/In.php',
                'rapture\\validator\\isempty' => '/../src/IsEmpty.php',
                'rapture\\validator\\isfalse' => '/../src/IsFalse.php',
                'rapture\\validator\\isnull' => '/../src/IsNull.php',
                'rapture\\validator\\istrue' => '/../src/IsTrue.php',
                'rapture\\validator\\length' => '/../src/Length.php',
                'rapture\\validator\\lessthan' => '/../src/LessThan.php',
                'rapture\\validator\\lessthanorequalto' => '/../src/LessThanOrEqualTo.php',
                'rapture\\validator\\locale' => '/../src/Locale.php',
                'rapture\\validator\\notempty' => '/../src/NotEmpty.php',
                'rapture\\validator\\notequalto' => '/../src/NotEqualTo.php',
                'rapture\\validator\\notidenticalto' => '/../src/NotIdenticalTo.php',
                'rapture\\validator\\notnull' => '/../src/NotNull.php',
                'rapture\\validator\\optional' => '/../src/Optional.php',
                'rapture\\validator\\password' => '/../src/Password.php',
                'rapture\\validator\\recaptcha' => '/../src/ReCaptcha.php',
                'rapture\\validator\\regex' => '/../src/Regex.php',
                'rapture\\validator\\required' => '/../src/Required.php',
                'rapture\\validator\\type' => '/../src/Type.php',
                'rapture\\validator\\url' => '/../src/Url.php',
                'rapture\\validator\\username' => '/../src/Username.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
